# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


### /api/{v}/account/{users_email}
GET http://localhost:20000/api/1.0/account/alklid@sample.com
Content-Type: application/json
Authorization: Bearer 473397ef-7864-4671-9d92-d4a83c6d15e0

###