# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


### /api/{v}/account/{users_email}
GET http://localhost:20000/v1/latest/users/alklid@sample.com
Content-Type: application/json
Authorization: Bearer 62c7812b-cfaa-4d84-ae8b-1d085591b61b

### /api/{v}/account/{users_email} - 403 denied
GET http://localhost:20000/v1/s1/users/alkli2@sample.com
Content-Type: application/json
Accept-Language: en-us
Authorization: Bearer 62c7812b-cfaa-4d84-ae8b-1d085591b61b

### /api/{v}/account/{users_email}
PUT http://localhost:20000/v1/s1/users/alklid@sample.com
Authorization: Bearer 62c7812b-cfaa-4d84-ae8b-1d085591b61b
Content-Type: application/json

{
  "name": "alklid",
  "dateUpdate": "2018-12-18T11:38:20Z"
}

###