# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


### /api/{v}/account/{users_email}
GET http://localhost:20000/v1/users/alklid@sample.com
Content-Type: application/json
Authorization: Bearer 9578321a-1da0-4b44-90c7-9a6c80bca830

### /api/{v}/account/{users_email} - 403 denied
GET http://localhost:20000/v1/users/alklid2@sample.com
Content-Type: application/json
Authorization: Bearer 9578321a-1da0-4b44-90c7-9a6c80bca830

### /api/{v}/account/{users_email}
PUT http://localhost:20000/v1/users/alklid@sample.com
Authorization: Bearer 9578321a-1da0-4b44-90c7-9a6c80bca830
Content-Type: application/json

{
  "name": "",
  "dateUpdate": "2018-12-18T11:38:20Z"
}

###