# spring
spring:
  profiles:
    active: ${ENVIRONMENT}
  # Must true if transaction base on CGLIB Proxy(default: true)
  aop:
    proxy-target-class: true
  # JPA
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        jdbc.time_zone: UTC

# version
api:
  build:
    version: D01C0120181209
  release:
    version: 0.9.1812.1


