# server
server:
  port: 20000
  tomcat:
    max-threads: 10
    max-connections: 100

# version
api:
  build:
    version: D01C0120181209
  release:
    version: 0.9.1812.1

# log
logging:
  level:
    ROOT: info
    org:
      hibernate:
        type: trace

# database
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/oauth_test
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      minimum-idle: 10
      maximum-pool-size : 20
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

