# server
server:
  port: 20000
  tomcat:
    max-threads: 10
    max-connections: 100

# version
api:
  build:
    version: D01C0120181209
  release:
    version: 0.9.1812.1

# Log level config
# logging.config=classpath:logback/logback.xml
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.orm: DEBUG
    org.springframework.transaction: ERROR
    org.hibernate.type: DEBUG
  path: ./logs
  file: ./logs/meditlink-openapi-auth

# spring
spring:
  profiles:
    active: local

# database
# TODO https://github.com/brettwooldridge/HikariCP mysql 설정 변경 필요
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        jdbc.time_zone: UTC
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/openapi_local_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: openapi
      password: openapi
      minimum-idle: 10
      maximum-pool-size : 20
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
      driver-class-name: com.mysql.jdbc.Driver

